[package]
name = "ship_6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buffer-graphics-lib = "0.18.0"
byteorder = "1.5.0"
mos6502 = "0.6.0"
pixels = "0.13.0"
tao = "0.20"
